### ISSUE TITLE
Quicksilver and Doppelganger

### ISSUE THREAD

**Issue by serpentiem** [serpentiem/ddmk#15]
Using Quicksilver while Doppelganger is active does not trigger Time Lag properly and traps Doppelganger in an update loop, ignoring style messages.

**Comment by serpentiem** [comment]
Fixed in [2.3](https://github.com/serpentiem/ddmk/releases/tag/2.3).

**Comment by adamkenway007** [comment]
hello serpentiem i've tried DDMK 2.3 and problem still occured on mission 7 player vergil.while fighting with hell vanguard using both Quicksilver then Doppleganger.trap Doppleganger still exists
