### ISSUE TITLE
DMC3 crashes upon multiple mission restarts

### ISSUE THREAD

**Issue by Zaphero1** [serpentiem/ddmk#196]
I'm not sure if it's an issue with the texture injection or just in general (I am using texture fixes for transparency and widescreen menus), but it seems like there's a memory leak upon reloading a level. After 2 or 3 mission restarts there's a high chance that the game will crash upon loading the opening cutscene of a mission or crash upon loading the mission after that cutscene. If I flat out just quit out of the mission and reload it that way, the crash never comes.

**Comment by cowboytanaka** [comment]
I'm pretty sure I have the same problem as you do but sometimes I've been able to play the mission a little bit before it crashes when loading an area. The first log is loading into the entranceway before the Enigma room in M4 and the second one is after the opening cutscene of M5.
[Mary 1.txt](https://github.com/serpentiem/ddmk/files/6328367/Mary.1.txt)
[Mary 2.txt](https://github.com/serpentiem/ddmk/files/6328368/Mary.2.txt)

**Comment by serpentiem** [comment]
Huh, interesting. I never considered that the cutscenes can cause leaks. I'll look into it!

**Comment by Zaphero1** [comment]
Yeah the crash still seems to be here on the newest version. The thing is that the cutscenes don't cause a leak they just seem to speed it up, which is why I think it's an issue with loading in in general, both for cutscenes and for the game. (For clarification I have done 0 saves as vergil in this dante save, and even then I still reset the weapon values and the crashes still happen.)
In 4 restarts of mission 1 here the game crashed for example, whereas mission 20 crashes in 2 or 3. Those are especially a problem because there's no advantage to continuing on those levels over restarting.
[Mary.txt](https://github.com/serpentiem/ddmk/files/6370782/Mary.txt)

**Comment by cowboytanaka** [comment]
I've been restarting M18 a lot (DMD 😔) on the newest version and it seems to always be after about 5 or 6 restarts.
[Mary.txt](https://github.com/serpentiem/ddmk/files/6371269/Mary.txt)
[Mary 2.txt](https://github.com/serpentiem/ddmk/files/6371270/Mary.2.txt)

**Comment by serpentiem** [comment]
Should be fixed with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly10).

**Comment by Zaphero1** [comment]
Doesn't seem like it is. Mission 20 still crashed after 3-5 restarts. Did the fix include the game over restart mission option? That's usually what I use.
[Mary.txt](https://github.com/serpentiem/ddmk/files/6373554/Mary.txt)

**Comment by serpentiem** [comment]
[Pikachu](https://tenor.com/view/surprised-pikachu-pokemon-shock-surprised-pikachu-gif-15357817)

**Comment by serpentiem** [comment]
Hopefully no Pikachu this time. [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly11)

**Comment by Zaphero1** [comment]
Yep! Game Over Restart has the workaround too and no crashes are happening. Thank you very much!

**Comment by serpentiem** [comment]
Glad it works!
